#
# NOTE: Any jobs not intended to run in a scheduled pipeline should have the following
# included as the first rule to prevent them being pulled in to those pipelines:
#   - if: $CI_PIPELINE_SOURCE == "schedule"
#     when: never

variables:
  NSPECT_ID: NSPECT-K66V-JJ0K
  DOCKER_IMG: nvmetal-carbide

  FORGE_ADMIN_CLI_IMAGE: nvcr.io/nvidian/dcim/forge-admin-cli
  APPLICATION_DOCKER_IMAGE: nvcr.io/nvidian/dcim/nvmetal-carbide
  ARTIFACTS_DOCKER_IMAGE_AARCH64: nvcr.io/nvidian/dcim/boot-artifacts-aarch64
  ARTIFACTS_DOCKER_IMAGE_X86_64: nvcr.io/nvidian/dcim/boot-artifacts-x86_64
  CARBIDE_EXTRAS_IMAGE: "urm.nvidia.com/swngc-ngcc-docker-local/forge/carbide-extras:latest"

  MACHINE_VALIDATION_ARTIFACTS_DOCKER_IMAGE: nvcr.io/nvidian/dcim/machine_validation
  MACHINE_VALIDATION_RUNNER_DOCKER_IMAGE: nvcr.io/nvidian/dcim/machine-validation-runner

  APPLICATION_DOCKER_IMAGE_PRODUCTION: nvcr.io/nvidian/dcim/nvmetal-carbide
  ARTIFACTS_DOCKER_IMAGE_AARCH64_PRODUCTION: nvcr.io/nvidian/dcim/boot-artifacts-aarch64
  ARTIFACTS_DOCKER_IMAGE_X86_64_PRODUCTION: nvcr.io/nvidian/dcim/boot-artifacts-x86_64
  MACHINE_VALIDATION_ARTIFACTS_DOCKER_IMAGE_PRODUCTION: nvcr.io/nvidian/dcim/machine_validation
  MACHINE_VALIDATION_RUNNER_DOCKER_IMAGE_PRODUCTION: nvcr.io/nvidian/dcim/machine-validation-runner
  POWERDNS_DOCKER_IMAGE: nvcr.io/nvidian/dcim/powerdns
  POWERDNS_VERSION: "4.9.11"
  SBOM_DOCKER_IMAGE: nvcr.io/nvidian/dcim/sbom-tools

  FF_USE_FASTZIP: "true" # enable fastzip - a faster zip implementation that also supports level configuration.
  ARTIFACT_COMPRESSION_LEVEL: default # can also be set to fastest, fast, slow and slowest. If just enabling fastzip is not enough try setting this to fastest or fast.
  CACHE_COMPRESSION_LEVEL: fastest
  TRANSFER_METER_FREQUENCY: 5s
  USE_GIT_HASH_VERSION: "true" # https://gitlab-master.nvidia.com/nvmetal/gitlab-templates/-/merge_requests/88

  KANIKO_CACHE_ARGS: "--cache=false --cache-copy-layers=true --cache-ttl=24h"
  APT_CACHE_DIR: $CI_PROJECT_DIR/apt
  CACHE_DIRECTORY: $CI_PROJECT_DIR/cache # for mkosi
  LOGNAME: root
  KEA_BIN_PATH: /usr/bin
  KEA_INCLUDE_PATH: /usr/include/kea

  CARGO_INCREMENTAL: 0
  CARGO_HOME: $CI_PROJECT_DIR/cargo
  NEED_HELM: "yes"

  FF_TIMESTAMPS: "true" # timestamp log output.

  #
  # Container Regsitries for intermediate containers (build & runtime), not for publishing.
  #
  CONTAINER_REGISTRY_AARCH64: "urm.nvidia.com/swngc-ngcc-docker-local/forge/rms-carbide/arm64v8"
  CONTAINER_REGISTRY_X86_64: "urm.nvidia.com/swngc-ngcc-docker-local/forge/rms-carbide/x86-64"


  # Canonical versions - will be overridden if you touch one of the dockerfiles that builds them
  #
  # How to update a build or runtime container.
  #
  # Make one commit where you update the Dockerfile in dev/docker.  Make an MR for it, it will build the new container and push it to urm in the MR.
  #
  # Next, *add* a commit to your MR where you update the relevant docker locations here.
  #
  # If you don't do the second step, merging to production will use the prior container.  I don't know how to solve this, but it's the way it was before
  #
  CONTAINER_BUILD_AARCH64: "urm.nvidia.com/swngc-ngcc-docker-local/forge/rms-carbide/arm64v8/build-container:latest"
  CONTAINER_BUILD_X86_64: "urm.nvidia.com/swngc-ngcc-docker-local/forge/rms-carbide/x86-64/build-container:latest"
  CONTAINER_FORGE_ADMIN_CLI_URM: "urm.nvidia.com/swngc-ngcc-docker-local/forge/rms-carbide/tools/forge-admin-cli:latest"
  CONTAINER_RUNTIME_AARCH64: "urm.nvidia.com/swngc-ngcc-docker-local/forge/rms-carbide/arm64v8/runtime-container:latest"
  CONTAINER_RUNTIME_X86_64: "urm.nvidia.com/swngc-ngcc-docker-local/forge/rms-carbide/x86-64/runtime-container:latest"
  CONTAINER_BUILD_ARTIFACTS_AARCH64: "urm.nvidia.com/swngc-ngcc-docker-local/forge/rms-carbide/arm64v8/build-artifacts-container:latest"
  CONTAINER_BUILD_ARTIFACTS_X86_64: "urm.nvidia.com/swngc-ngcc-docker-local/forge/rms-carbide/x86-64/build-artifacts-container:latest"
  CONTAINER_ARTIFACTS_X86_64: "alpine:latest"
  CONTAINER_ARTIFACTS_AARCH64: "alpine:latest"

default:
  tags:
    - x86_64

include:
  - project: "swserver/gitlab-templates"
    ref: main
    file:
      - defaults.gitlab-ci.yml
  - project: pstooling/gitlab-templates
    ref: main
    file: templates/pulse-in-pipeline/ContainerScan.gitlab-ci.yml
  - project: 'pstooling/gitlab-templates'
    ref: main
    file:
      - 'templates/pulse-in-pipeline/Scan.gitlab-ci.yml'

prepare-ci:
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_COMMIT_BRANCH =~ /^release\//
    - if: $CI_PIPELINE_SOURCE

build:
  rules:
    - when: never

build-push-helm:
  rules:
    - when: never

build-push-kustomize:
  rules:
    - when: never

notify-security-report:
  rules:
    - when: never

prepare-kustomize-for-scan:
  rules:
    - when: never

build-container:
  rules:
    - when: never

checkmarx-scan-csv:
  rules:
    - when: never

checkov-scan:
  rules:
    - when: never

container-scan:
  rules:
    - when: never

pulse-open-source:
  rules:
    - when: never

export-docker-json-config:
  when: always

#
# Build the container that builds our software
#
build-build-container-x86_64:
  stage: build
  needs:
    - job: prepare-ci
      optional: false
  extends: build-container
  variables:
    DOCKER_FILE: $CI_PROJECT_DIR/dev/docker/Dockerfile.build-container-x86_64
    BUILD_DOCKER_IMAGE: urm.nvidia.com/swngc-ngcc-docker-local/forge/$CI_PROJECT_NAME/x86-64/build-container
  after_script:
    - echo "CONTAINER_BUILD_X86_64=$CONTAINER_REGISTRY_X86_64/build-container:$VERSION" > build-container-x86_64.env
    - echo "CONTAINER_BUILD_X86_64_WAS_BUILT=true" >> build-container-x86_64.env
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_COMMIT_MESSAGE =~ /ci-rebuild-base-containers/
    - changes:
        - dev/docker/Dockerfile.build-container-x86_64
  artifacts:
    reports:
      dotenv: build-container-x86_64.env

#
# ARM version uses kaniko instead of extending build-container because devops-tools doesn't have an ARM version
#
build-build-container-aarch64:
  stage: build
  needs:
    - job: prepare-ci
      optional: false
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  variables:
    DOCKER_FILE: $CI_PROJECT_DIR/dev/docker/Dockerfile.build-container-aarch64
    BUILD_DOCKER_IMAGE: urm.nvidia.com/swngc-ngcc-docker-local/forge/$CI_PROJECT_NAME/arm64v8/build-container
  before_script: |
    mkdir -p /kaniko/.docker
    echo "$DOCKER_AUTH_CONFIG" > /kaniko/.docker/config.json
  script: |
    set -xeuo pipefail
    /kaniko/executor --context $CI_PROJECT_DIR/dev/docker --dockerfile $DOCKER_FILE --destination $BUILD_DOCKER_IMAGE:$VERSION
  tags:
    - aarch64-docker
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_COMMIT_MESSAGE =~ /ci-rebuild-base-containers/
    - changes:
        - dev/docker/Dockerfile.build-container-aarch64
  after_script:
    - echo "CONTAINER_BUILD_AARCH64=$CONTAINER_REGISTRY_AARCH64/build-container:$VERSION" > build-container-aarch64.env
    - echo "CONTAINER_BUILD_AARCH64_WAS_BUILT=true" >> build-container-aarch64.env
  artifacts:
    reports:
      dotenv: build-container-aarch64.env

#
# Build the container that builds our software
#
build-artifacts-build-container-x86_64:
  stage: build
  needs:
    - job: prepare-ci
      optional: false
  extends: build-container
  variables:
    DOCKER_FILE: $CI_PROJECT_DIR/dev/docker/Dockerfile.build-artifacts-container-x86_64
    BUILD_DOCKER_IMAGE: urm.nvidia.com/swngc-ngcc-docker-local/forge/$CI_PROJECT_NAME/x86-64/build-artifacts-container
  after_script:
    - echo "CONTAINER_BUILD_ARTIFACTS_X86_64=$CONTAINER_REGISTRY_X86_64/build-artifacts-container:$VERSION" > build-artifacts-container-x86_64.env
    - echo "CONTAINER_BUILD_ARTIFACTS_X86_64_WAS_BUILT=true" >> build-artifacts-container-x86_64.env
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_COMMIT_MESSAGE =~ /ci-rebuild-base-containers/
    - changes:
        - dev/docker/Dockerfile.build-artifacts-container-x86_64
  artifacts:
    reports:
      dotenv: build-artifacts-container-x86_64.env

#
# ARM version uses kaniko instead of extending build-container because devops-tools doesn't have an ARM version
#
build-artifacts-build-container-aarch64:
  stage: build
  needs:
    - job: prepare-ci
      optional: false
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  variables:
    DOCKER_FILE: $CI_PROJECT_DIR/dev/docker/Dockerfile.build-artifacts-container-aarch64
    BUILD_DOCKER_IMAGE: urm.nvidia.com/swngc-ngcc-docker-local/forge/$CI_PROJECT_NAME/arm64v8/build-artifacts-container
  before_script: |
    mkdir -p /kaniko/.docker
    echo "$DOCKER_AUTH_CONFIG" > /kaniko/.docker/config.json
  script: |
    set -xeuo pipefail
    /kaniko/executor --context $CI_PROJECT_DIR/dev/docker --dockerfile $DOCKER_FILE --destination $BUILD_DOCKER_IMAGE:$VERSION
  tags:
    - aarch64-docker
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_COMMIT_MESSAGE =~ /ci-rebuild-base-containers/
    - changes:
        - dev/docker/Dockerfile.build-artifacts-container-aarch64
  after_script:
    - echo "CONTAINER_BUILD_ARTIFACTS_AARCH64=$CONTAINER_REGISTRY_AARCH64/build-artifacts-container:$VERSION" > build-artifacts-container-aarch64.env
    - echo "CONTAINER_BUILD_ARTIFACTS_AARCH64_WAS_BUILT=true" >> build-artifacts-container-aarch64.env
  artifacts:
    reports:
      dotenv: build-artifacts-container-aarch64.env

#
# Build the container that will host the finalized carbide code.
#
build-runtime-container-x86_64:
  stage: build
  needs:
    - job: prepare-ci
      optional: false
  extends: build-container
  variables:
    DOCKER_FILE: $CI_PROJECT_DIR/dev/docker/Dockerfile.runtime-container-x86_64
    BUILD_DOCKER_IMAGE: urm.nvidia.com/swngc-ngcc-docker-local/forge/$CI_PROJECT_NAME/x86-64/runtime-container
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_COMMIT_MESSAGE =~ /ci-rebuild-base-containers/
    - changes:
        - dev/docker/Dockerfile.runtime-container-x86_64
  after_script:
    - echo "CONTAINER_RUNTIME_X86_64=$CONTAINER_REGISTRY_X86_64/runtime-container:$VERSION" > runtime-container-x86_64.env
    - echo "CONTAINER_RUNTIME_X86_64_WAS_BUILT==true" >> runtime-container-x86_64.env
  artifacts:
    reports:
      dotenv: runtime-container-x86_64.env

#
# ARM version uses kaniko instead of extending build-container because devops-tools doesn't have an ARM version
#
build-runtime-container-aarch64:
  stage: build
  needs:
    - job: prepare-ci
      optional: false
  variables:
    DOCKER_FILE: $CI_PROJECT_DIR/dev/docker/Dockerfile.runtime-container-aarch64
    BUILD_DOCKER_IMAGE: urm.nvidia.com/swngc-ngcc-docker-local/forge/$CI_PROJECT_NAME/arm64v8/runtime-container
  tags:
    - aarch64
  script: /bin/true
  rules:
    - when: never # TODO - we don't run carbide on ARM yet
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
#    - if: $CI_COMMIT_MESSAGE =~ /ci-rebuild-base-containers/
#    - changes:
#        - dev/docker/Dockerfile.runtime-container-aarch64
  after_script:
    - echo "CONTAINER_RUNTIME_AARCH64=$CONTAINER_REGISTRY_AARCH64/runtime-container:$VERSION" > runtime-container-aarch64.env
    - echo "CONTAINER_RUNTIME_AARCH64_WAS_BUILT=true" >> runtime-container-aarch64.env
  artifacts:
    reports:
      dotenv: runtime-container-aarch64.env

#
# When a new build/runtime/artifacts container is built, and we're on the
# trunk/main branch, then make sure we tag it with 'latest' so that subsequent
# jobs will use it.
#
tag-build-and-runtime-containers:
  stage: publish
  image:
    name: gcr.io/go-containerregistry/crane:debug
    entrypoint: [""]
  needs:
    - job: prepare-ci
      optional: false
    - job: export-docker-json-config
      optional: false
    - job: build-build-container-x86_64
      optional: true
    - job: build-build-container-aarch64
      optional: true
    - job: build-runtime-container-x86_64
      optional: true
    - job: build-runtime-container-aarch64
      optional: true
    - job: build-artifacts-build-container-x86_64
      optional: true
    - job: build-artifacts-build-container-aarch64
      optional: true
  allow_failure: true
  before_script: |
    mkdir -p /root/.docker
    cp .docker/config.json /root/.docker/config.json
  script: |
    set -xeuo pipefail

    if [ ! -z "${CONTAINER_BUILD_X86_64_WAS_BUILT:-}" ]; then
      crane copy "${CONTAINER_BUILD_X86_64}" "${CONTAINER_REGISTRY_X86_64}/build-container:latest"
    fi

    if [ ! -z "${CONTAINER_BUILD_AARCH64_WAS_BUILT:-}" ]; then
      crane copy "${CONTAINER_BUILD_AARCH64}" "${CONTAINER_REGISTRY_AARCH64}/build-container:latest"
    fi

    if [ ! -z "${CONTAINER_BUILD_ARTIFACTS_X86_64_WAS_BUILT:-}" ]; then
      crane copy "${CONTAINER_BUILD_ARTIFACTS_X86_64}" "${CONTAINER_REGISTRY_X86_64}/build-artifacts-container:latest"
    fi

    if [ ! -z "${CONTAINER_BUILD_ARTIFACTS_AARCH64_WAS_BUILT:-}" ]; then
      crane copy "${CONTAINER_BUILD_ARTIFACTS_AARCH64}" "${CONTAINER_REGISTRY_AARCH64}/build-artifacts-container:latest"
    fi

    if [ ! -z "${CONTAINER_RUNTIME_X86_64_WAS_BUILT:-}" ]; then
      crane copy "${CONTAINER_RUNTIME_X86_64}" "${CONTAINER_REGISTRY_X86_64}/runtime-container:latest"
    fi

    if [ ! -z "${CONTAINER_RUNTIME_AARCH64_WAS_BUILT:-}" ]; then
      crane copy  "${CONTAINER_RUNTIME_AARCH64}" "${CONTAINER_REGISTRY_AARCH64}/runtime-container:latest"
    fi

  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH || $CI_COMMIT_MESSAGE =~ /ci-run-complete-pipeline/ || $CI_COMMIT_BRANCH =~ /^release\//

#
# Build the final container that releases our code
#
build-release-container-x86_64:
  stage: build
  extends: build-push-container
  needs:
    - job: prepare-ci
      optional: false
    - job: build-build-container-x86_64
      optional: true
    - job: build-runtime-container-x86_64
      optional: true
  variables:
    DOCKER_FILE: $CI_PROJECT_DIR/dev/docker/Dockerfile.release-container-x86_64
    FF_TIMESTAMPS: true
  script:
    - docker build -t intermediate-container-$CI_COMMIT_SHORT_SHA -f $DOCKER_FILE --build-arg VERSION=$VERSION --build-arg CI_COMMIT_SHORT_SHA=$CI_COMMIT_SHORT_SHA --build-arg CONTAINER_RUNTIME_X86_64=$CONTAINER_RUNTIME_X86_64 --build-arg CONTAINER_BUILD_X86_64=$CONTAINER_BUILD_X86_64 .
    - |
        if test "$DEPLOY_BUILT_CONTAINER" = "true"; then
          echo "Deploying build container: intermediate-container-$CI_COMMIT_SHORT_SHA to $APPLICATION_DOCKER_IMAGE:$VERSION"
          docker tag "intermediate-container-$CI_COMMIT_SHORT_SHA" "$APPLICATION_DOCKER_IMAGE:$VERSION"
          docker push "$APPLICATION_DOCKER_IMAGE:$VERSION"
          docker rmi "$APPLICATION_DOCKER_IMAGE:$VERSION"
        else
          echo "Skipping deployment of intermediate-container-$CI_COMMIT_SHORT_SHA"
        fi
    - docker rmi intermediate-container-$CI_COMMIT_SHORT_SHA
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_COMMIT_BRANCH =~ /^release\//  # Run for default and those starting with "release/"
      variables:
        DEPLOY_BUILT_CONTAINER: "true"
    - if: $CI_COMMIT_TAG || $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH || $CI_COMMIT_MESSAGE =~ /ci-run-complete-pipeline/
      variables:
        DEPLOY_BUILT_CONTAINER: "true"
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      variables:
        DEPLOY_BUILT_CONTAINER: "false"
  after_script:
    - echo "CONTAINER_RELEASE_X86_64=$APPLICATION_DOCKER_IMAGE:$VERSION" > release-container-x86_64.env
  artifacts:
    reports:
      dotenv: release-container-x86_64.env


build-container-forge-cli-x86_64:
  stage: build
  extends: build-push-container
  needs:
    - job: prepare-ci
      optional: false
    - job: export-docker-json-config
      optional: false
    - job: build-artifacts-build-container-x86_64
      optional: true
  variables:
    DOCKER_FILE: $CI_PROJECT_DIR/dev/docker/Dockerfile.release-forge-cli
  dependencies:
    - prepare-ci
    - export-docker-json-config
  tags:
    - x86_64
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  before_script: |
    set -euo pipefail
    mkdir -p /kaniko/.docker
    cp .docker/config.json /kaniko/.docker/config.json
    export VAULT_JWT_ROLE=$VAULT_JWT_ROLE_FORGE
    export VAULT_JWT_PATH=$VAULT_JWT_PATH_FORGE
    export VAULT_TOKEN="$(vault write -field=token $VAULT_JWT_PATH role=$VAULT_JWT_ROLE jwt=$VAULT_JWT_TOKEN)"
  script:
    - >-
      /kaniko/executor --context "${CI_PROJECT_DIR}" --dockerfile "${DOCKER_FILE}" --build-arg "CI_COMMIT_SHORT_SHA=$CI_COMMIT_SHORT_SHA" --build-arg "CONTAINER_BUILD=$CONTAINER_BUILD_ARTIFACTS_X86_64" --destination "${FORGE_ADMIN_CLI_IMAGE}-${VERSION}:amd64"
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_COMMIT_TAG || $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH || $CI_COMMIT_MESSAGE =~ /ci-run-complete-pipeline/
      variables:
        KANIKO_NO_PUSH: "false"
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      variables:
        KANIKO_NO_PUSH: "true"

build-container-forge-cli-aarch64:
  stage: build
  extends: build-push-container
  needs:
    - job: prepare-ci
      optional: false
    - job: export-docker-json-config
      optional: false
    - job: build-artifacts-build-container-aarch64
      optional: true
  variables:
    DOCKER_FILE: $CI_PROJECT_DIR/dev/docker/Dockerfile.release-forge-cli
  dependencies:
    - prepare-ci
    - export-docker-json-config
  tags:
    - aarch64-docker
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  before_script: |
    set -euo pipefail
    mkdir -p /kaniko/.docker
    cp .docker/config.json /kaniko/.docker/config.json
    export VAULT_JWT_ROLE=$VAULT_JWT_ROLE_FORGE
    export VAULT_JWT_PATH=$VAULT_JWT_PATH_FORGE
    export VAULT_TOKEN="$(vault write -field=token $VAULT_JWT_PATH role=$VAULT_JWT_ROLE jwt=$VAULT_JWT_TOKEN)"
  script:
    - >-
      /kaniko/executor --context "${CI_PROJECT_DIR}" --dockerfile "${DOCKER_FILE}" --build-arg "CI_COMMIT_SHORT_SHA=$CI_COMMIT_SHORT_SHA" --build-arg "CONTAINER_BUILD=$CONTAINER_BUILD_ARTIFACTS_AARCH64" --destination "${FORGE_ADMIN_CLI_IMAGE}-${VERSION}:arm64"
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_COMMIT_TAG || $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH || $CI_COMMIT_MESSAGE =~ /ci-run-complete-pipeline/
      variables:
        KANIKO_NO_PUSH: "false"
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      variables:
        KANIKO_NO_PUSH: "true"

merge-manifests-forge-cli:
  stage: build
  # all containers must be build before merging them
  # alternatively the job may be configured to run in a later stage
  needs:
    - job: prepare-ci
      optional: false
    - job: export-docker-json-config
      optional: false
    - job: build-container-forge-cli-aarch64
      artifacts: false
    - job: build-container-forge-cli-x86_64
      artifacts: false
  before_script: |
    mkdir -p /kaniko/.docker
    cp .docker/config.json /kaniko/.docker/config.json
  tags:
    # may run on any architecture supported by manifest-tool image
    - x86_64
  image:
    name: mplatform/manifest-tool:alpine
    entrypoint: [""]
  script:
    - >-
      manifest-tool --docker-cfg .docker/config.json push from-args --platforms linux/amd64,linux/arm64 --template "${FORGE_ADMIN_CLI_IMAGE}-${VERSION}:ARCH" --tags latest --target "${FORGE_ADMIN_CLI_IMAGE}:${VERSION}"
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_COMMIT_TAG || $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH || $CI_COMMIT_MESSAGE =~ /ci-run-complete-pipeline/
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: never

# Copy the final multi-arch container to urm for use in QA automation
copy-carbide-admin-cli-to-urm:
  stage: build
  needs:
    - job: prepare-ci
      optional: false
    - job: export-docker-json-config
      optional: false
    - job: merge-manifests-forge-cli
      optional: false
    - job: get-crane
      optional: false
  image:
    name: gcr.io/go-containerregistry/crane:debug
    entrypoint: [""]
  tags:
    - x86_64
  before_script:
    - mkdir -p /root/.docker
    - cp .docker/config.json /root/.docker/config.json
  script:
    - echo "Copying ${FORGE_ADMIN_CLI_IMAGE}:latest to ${CONTAINER_FORGE_ADMIN_CLI_URM}"
    - ./crane copy "${FORGE_ADMIN_CLI_IMAGE}:latest" "${CONTAINER_FORGE_ADMIN_CLI_URM}"
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_COMMIT_TAG || $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH || $CI_COMMIT_MESSAGE =~ /ci-run-complete-pipeline/
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: never


#
# Build the final container that releases our code
#
.build-boot-artifacts:
  stage: build
  variables:
    FORGE_CA: "prod"
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - when: always

build-boot-artifacts-x86-host:
  extends: .build-boot-artifacts
  needs:
    - job: prepare-ci
      optional: false
    - job: build-artifacts-build-container-x86_64
      optional: true
  image:
    name: $CONTAINER_BUILD_ARTIFACTS_X86_64
  script:
    - cargo make --cwd pxe build-boot-artifacts-x86-host-ci
  artifacts:
    paths:
      - pxe/static/blobs/internal/x86_64/ipxe.efi
      - target/debug/carbide-admin-cli
      - target/debs/*
    when: always
    expire_in: 1 day

build-boot-artifacts-bfb:
  extends: .build-boot-artifacts
  timeout: 2h
  needs:
    - job: prepare-ci
      optional: false
    - job: build-artifacts-build-container-aarch64
      optional: true
  tags:
    - aarch64-docker # not shell because no mkosi aarch64 image
  image:
    name: $CONTAINER_BUILD_ARTIFACTS_AARCH64
  script:
    - cargo make --cwd pxe build-boot-artifacts-bfb-ci
  artifacts:
    paths:
      - pxe/static/blobs/internal/aarch64/secure-boot-pk.pem
      - pxe/static/blobs/internal/aarch64/ipxe.efi
      - pxe/static/blobs/internal/aarch64/carbide.efi
      - pxe/static/blobs/internal/aarch64/carbide.root
      - pxe/static/blobs/internal/aarch64/preingestion.bfb
      - pxe/static/blobs/internal/aarch64/forge.bfb
      - pxe/static/blobs/internal/apt
      - target/aarch64-unknown-linux-gnu/release/forge-scout
      - target/debs/*
    when: always
    expire_in: 1 day

# This just builds the mkosi container and uses artifacts from a previous build
build-boot-artifacts-ephemeral-image-x86-host:
  extends: .build-boot-artifacts
  needs:
    - job: prepare-ci
      optional: false
    - job: export-docker-json-config
      optional: false
    - job: build-boot-artifacts-x86-host
      optional: false
  dependencies:
    - build-boot-artifacts-x86-host
    - export-docker-json-config
  tags:
    - shell # mkosi cannot run in docker :(
    - ukify
    - mkosi
  variables:
    PROFILE: scout-oss-x86_64
    VAULT_NAMESPACE: tesla-dcss-rms
  id_tokens:
    VAULT_JWT_TOKEN:
      aud: $VAULT_ADDR
  image:
    name: $CONTAINER_BUILD_ARTIFACTS_AARCH64
  before_script:
    - set -euo pipefail
    - mkdir -p ~/.docker
    - cp .docker/config.json ~/.docker/config.json
    - export VAULT_JWT_ROLE=$VAULT_JWT_ROLE_FORGE
    - export VAULT_JWT_PATH=$VAULT_JWT_PATH_FORGE
    - export VAULT_TOKEN="$(vault write -field=token $VAULT_JWT_PATH role=$VAULT_JWT_ROLE jwt=$VAULT_JWT_TOKEN)"
  script:
    # Pull and extract extras from container
    - docker pull "${CARBIDE_EXTRAS_IMAGE}"
    - container_id=$(docker create "${CARBIDE_EXTRAS_IMAGE}" /bin/true)
    - mkdir -p pxe/.scout-extras
    - docker cp "${container_id}:/extras/." pxe/.scout-extras/
    - docker rm "${container_id}"

    # Copy extras to build-output/extras/
    - PROFILE_DIR="pxe/mkosi.profiles/${PROFILE}"
    - mkdir -p "${PROFILE_DIR}/mkosi.extra/build-output"
    - cp -a pxe/.scout-extras "${PROFILE_DIR}/mkosi.extra/build-output/extras"

    # Append postinst
    - cat pxe/.scout-extras/postinst-extras.sh >> "${PROFILE_DIR}/mkosi.postinst.chroot"

    # Build
    - cargo install cargo-make
    - cargo make --cwd pxe create-ephemeral-image-x86-host-ci
  artifacts:
    paths:
      - target/debs/*
      - pxe/static/blobs/internal/x86_64/scout.efi
      - pxe/static/blobs/internal/x86_64/scout.cpio.zst
      - pxe/static/blobs/internal/x86_64/qcow-imager.efi
    when: always
    expire_in: 1 day

build-release-artifacts-x86-host:
  stage: build
  extends: build-push-container
  needs:
    - job: prepare-ci
      optional: false
    - job: build-boot-artifacts-x86-host
      optional: false
    - job: build-boot-artifacts-ephemeral-image-x86-host
      optional: false
  dependencies:
    - build-boot-artifacts-ephemeral-image-x86-host
    - build-boot-artifacts-x86-host
    - prepare-ci
  variables:
    DOCKER_FILE: $CI_PROJECT_DIR/dev/docker/Dockerfile.release-artifacts-x86_64
  script:
    - docker build -t intermediate-artifacts-$CI_COMMIT_SHORT_SHA -f $DOCKER_FILE --build-arg VERSION=$VERSION --build-arg CI_COMMIT_SHORT_SHA=$CI_COMMIT_SHORT_SHA --build-arg CONTAINER_RUNTIME_X86_64=$CONTAINER_ARTIFACTS_X86_64 .
    - |
        if test "$DEPLOY_BUILT_CONTAINER" = "true"; then
          echo "Deploying build container: intermediate-artifacts-$CI_COMMIT_SHORT_SHA to $ARTIFACTS_DOCKER_IMAGE_X86_64:$VERSION"
          docker tag "intermediate-artifacts-$CI_COMMIT_SHORT_SHA" "$ARTIFACTS_DOCKER_IMAGE_X86_64:$VERSION"
          docker push "$ARTIFACTS_DOCKER_IMAGE_X86_64:$VERSION"
        else
          echo "Skipping deployment of intermediate-artifacts-$CI_COMMIT_SHORT_SHA"
        fi
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_COMMIT_TAG || $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH || $CI_COMMIT_MESSAGE =~ /ci-run-complete-pipeline/ || $CI_COMMIT_BRANCH =~ /^release\//
      variables:
        DEPLOY_BUILT_CONTAINER: "true"
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      variables:
        DEPLOY_BUILT_CONTAINER: "false"

build-release-machine-validation-artifacts-x86-host:
  stage: build
  extends: build-push-container
  needs:
    - job: prepare-ci
      optional: false
    - job: build-release-machine-validation-runner
      optional: false
  dependencies:
    - prepare-ci
    - build-release-machine-validation-runner
  variables:
    DOCKER_FILE: $CI_PROJECT_DIR/dev/docker/Dockerfile.machine-validation-config
  script:
    - docker build -t intermediate-artifacts-$CI_COMMIT_SHORT_SHA -f $DOCKER_FILE --build-arg VERSION=$VERSION --build-arg CI_COMMIT_SHORT_SHA=$CI_COMMIT_SHORT_SHA --build-arg CONTAINER_RUNTIME_X86_64=$CONTAINER_ARTIFACTS_X86_64 .
    - |
        if test "$DEPLOY_BUILT_CONTAINER" = "true"; then
          echo "Deploying build container: intermediate-artifacts-$CI_COMMIT_SHORT_SHA to $MACHINE_VALIDATION_ARTIFACTS_DOCKER_IMAGE:$VERSION"
          docker tag "intermediate-artifacts-$CI_COMMIT_SHORT_SHA" "$MACHINE_VALIDATION_ARTIFACTS_DOCKER_IMAGE:$VERSION"
          docker push "$MACHINE_VALIDATION_ARTIFACTS_DOCKER_IMAGE:$VERSION"
        else
          echo "Skipping deployment of intermediate-artifacts-$CI_COMMIT_SHORT_SHA"
        fi
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_COMMIT_TAG || $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH || $CI_COMMIT_MESSAGE =~ /ci-run-complete-pipeline/ || $CI_COMMIT_BRANCH =~ /^release\//
      variables:
        DEPLOY_BUILT_CONTAINER: "true"
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      variables:
        DEPLOY_BUILT_CONTAINER: "false"

build-release-machine-validation-runner:
  stage: build
  extends: build-push-container
  needs:
    - job: prepare-ci
      optional: false
  dependencies:
    - prepare-ci
  variables:
    DOCKER_FILE: $CI_PROJECT_DIR/dev/docker/Dockerfile.machine-validation-runner
  script:
    - docker build -t intermediate-artifacts-$CI_COMMIT_SHORT_SHA -f $DOCKER_FILE --build-arg VERSION=$VERSION --build-arg CI_COMMIT_SHORT_SHA=$CI_COMMIT_SHORT_SHA --build-arg CONTAINER_RUNTIME_X86_64=$CONTAINER_ARTIFACTS_X86_64 .
    - docker tag "intermediate-artifacts-$CI_COMMIT_SHORT_SHA" $MACHINE_VALIDATION_RUNNER_DOCKER_IMAGE_PRODUCTION:latest
    - docker save --output crates/machine-validation/images/machine-validation-runner.tar $MACHINE_VALIDATION_RUNNER_DOCKER_IMAGE_PRODUCTION:latest
    - |
        echo "In case if there is registry access. May not be required Check later"
        if test "$DEPLOY_BUILT_CONTAINER" = "true"; then
          echo "Deploying build container: intermediate-artifacts-$CI_COMMIT_SHORT_SHA to $MACHINE_VALIDATION_RUNNER_DOCKER_IMAGE:$VERSION"
          docker tag "intermediate-artifacts-$CI_COMMIT_SHORT_SHA" "$MACHINE_VALIDATION_RUNNER_DOCKER_IMAGE:$VERSION"
          docker push "$MACHINE_VALIDATION_RUNNER_DOCKER_IMAGE:$VERSION"
        else
          echo "Skipping deployment of intermediate-artifacts-$CI_COMMIT_SHORT_SHA"
        fi
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_COMMIT_TAG || $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH || $CI_COMMIT_MESSAGE =~ /ci-run-complete-pipeline/ || $CI_COMMIT_BRANCH =~ /^release\//
      variables:
        DEPLOY_BUILT_CONTAINER: "true"
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      variables:
        DEPLOY_BUILT_CONTAINER: "false"
  artifacts:
    paths:
      - crates/machine-validation/images
    when: always
    expire_in: 1 day

# This just builds the mkosi container and uses artifacts from a previous build
# This relies on the bfb build to get an arm version of scout
build-boot-artifacts-ephemeral-image-arm-host:
  extends: .build-boot-artifacts
  needs:
    - job: prepare-ci
      optional: false
    - job: export-docker-json-config
      optional: false
    - job: build-boot-artifacts-bfb
      optional: false
  dependencies:
    - build-boot-artifacts-bfb
    - export-docker-json-config
  tags:
    - aarch64-shell
  variables:
    PROFILE: scout-oss-aarch64
    VAULT_NAMESPACE: tesla-dcss-rms
  id_tokens:
    VAULT_JWT_TOKEN:
      aud: $VAULT_ADDR
  before_script:
    - set -euo pipefail
    - mkdir -p ~/.docker
    - cp .docker/config.json ~/.docker/config.json
    - export VAULT_JWT_ROLE=$VAULT_JWT_ROLE_FORGE
    - export VAULT_JWT_PATH=$VAULT_JWT_PATH_FORGE
    - export VAULT_TOKEN="$(vault write -field=token $VAULT_JWT_PATH role=$VAULT_JWT_ROLE jwt=$VAULT_JWT_TOKEN)"
    - echo "kernel.apparmor_restrict_unprivileged_userns=0" | sudo tee /etc/sysctl.d/99-userns.conf
    - sudo sysctl --system
  script:
    # Pull and extract extras from container
    - docker pull "${CARBIDE_EXTRAS_IMAGE}"
    - container_id=$(docker create "${CARBIDE_EXTRAS_IMAGE}" /bin/true)
    - mkdir -p pxe/.scout-extras
    - docker cp "${container_id}:/extras/." pxe/.scout-extras/
    - docker rm "${container_id}"

    # Copy extras to build-output/extras/
    - PROFILE_DIR="pxe/mkosi.profiles/${PROFILE}"
    - mkdir -p "${PROFILE_DIR}/mkosi.extra/build-output"
    - cp -a pxe/.scout-extras "${PROFILE_DIR}/mkosi.extra/build-output/extras"

    # Append postinst
    - cat pxe/.scout-extras/postinst-extras.sh >> "${PROFILE_DIR}/mkosi.postinst.chroot"

    #Build
    - cargo install cargo-make
    - cargo make --cwd pxe create-ephemeral-image-arm-host-ci
  artifacts:
    paths:
      - target/debs/*
      - pxe/mkosi.profiles/scout-oss-aarch64/mkosi.extra/build-output/*
      - pxe/static/blobs/internal/aarch64/scout.efi
      - pxe/static/blobs/internal/aarch64/qcow-imager.efi
      - pxe/static/blobs/internal/aarch64/scout.cpio.zst
    when: always
    expire_in: 1 day

build-release-artifacts-arm-host:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  tags:
    - x86_64 # The AARCH64 artifacts are still packaged into the X86_64 version of the image because we execute commands in it on an X86_64 host
  needs:
    - job: prepare-ci
      optional: false
    - job: export-docker-json-config
      optional: false
    - job: build-runtime-container-x86_64
      optional: true
    - job: build-boot-artifacts-bfb
      optional: false
    - job: build-boot-artifacts-ephemeral-image-arm-host
      optional: false
  dependencies:
    - build-boot-artifacts-bfb
    - prepare-ci
    - export-docker-json-config
    - build-boot-artifacts-ephemeral-image-arm-host
  variables:
    DOCKER_FILE: $CI_PROJECT_DIR/dev/docker/Dockerfile.release-artifacts-aarch64
  before_script: |
    mkdir -p /kaniko/.docker
    cp .docker/config.json /kaniko/.docker/config.json
  script: |
    set -euo pipefail
    if test "$DEPLOY_BUILT_CONTAINER" = "true"; then
      echo "Deploying container: $ARTIFACTS_DOCKER_IMAGE_AARCH64:$VERSION"

      # The AARCH64 artifacts are still packaged into the X86_64 version of the image because we execute commands in it on an X86_64 host
      /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $DOCKER_FILE --build-arg "CI_COMMIT_SHORT_SHA=$CI_COMMIT_SHORT_SHA" --build-arg "CONTAINER_RUNTIME_AARCH64=$CONTAINER_ARTIFACTS_X86_64" --destination "$ARTIFACTS_DOCKER_IMAGE_AARCH64:$VERSION"
    else
      echo "Skipping deployment of $ARTIFACTS_DOCKER_IMAGE_AARCH64:$VERSION"

      # The AARCH64 artifacts are still packaged into the X86_64 version of the image because we execute commands in it on an X86_64 host
      /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $DOCKER_FILE --build-arg "CI_COMMIT_SHORT_SHA=$CI_COMMIT_SHORT_SHA" --build-arg "CONTAINER_RUNTIME_AARCH64=$CONTAINER_ARTIFACTS_X86_64" --no-push
    fi
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_COMMIT_TAG || $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH || $CI_COMMIT_MESSAGE =~ /ci-run-complete-pipeline/ || $CI_COMMIT_BRANCH =~ /^release\//
      variables:
        DEPLOY_BUILT_CONTAINER: "true"
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      variables:
        DEPLOY_BUILT_CONTAINER: "false"

get-crane:
  stage: .pre
  image:
    name: gcr.io/go-containerregistry/crane:debug
    entrypoint: [""]
  variables:
    PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/busybox:/ko-app
  script:
    - cp $(which crane) .
  artifacts:
    paths:
      - crane
    when: always
    expire_in: 1 day
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - when: always

proto-police:
  stage: .pre
  image:
    name: yoheimuta/protolint
    entrypoint: [""]
  script:
    - protolint lint -config_path=.protolint.yaml --reporter ci-glab crates/rpc/proto/
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - "**/*.proto"

build-sbom-container:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  needs:
    - job: prepare-ci
      optional: false
    - job: export-docker-json-config
      optional: false
  dependencies:
    - prepare-ci
    - export-docker-json-config
  variables:
    DOCKER_FILE: $CI_PROJECT_DIR/dev/docker/sbom-tools/Dockerfile
  before_script: |
    mkdir -p /kaniko/.docker
    cp .docker/config.json /kaniko/.docker/config.json
  script: |
    set -euo pipefail
    /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $DOCKER_FILE --build-arg "CI_COMMIT_SHORT_SHA=$CI_COMMIT_SHORT_SHA"  --destination "$SBOM_DOCKER_IMAGE:$VERSION" --destination "$SBOM_DOCKER_IMAGE:latest"
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_COMMIT_MESSAGE =~ /ci-rebuild-sbom-tools/
    - if: $REBUILD_SBOM_CONTAINER == "true"
    - changes:
        - dev/docker/sbom-tools/Dockerfile


build-powerdns-container:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  needs:
    - job: prepare-ci
      optional: false
    - job: export-docker-json-config
      optional: false
  dependencies:
    - prepare-ci
    - export-docker-json-config
  variables:
    DOCKER_FILE: $CI_PROJECT_DIR/dev/docker/powerdns/Dockerfile
  before_script: |
    mkdir -p /kaniko/.docker
    cp .docker/config.json /kaniko/.docker/config.json
  script: |
    set -euo pipefail
    /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $DOCKER_FILE --build-arg "CI_COMMIT_SHORT_SHA=$CI_COMMIT_SHORT_SHA"  --destination "$POWERDNS_DOCKER_IMAGE:$POWERDNS_VERSION" --destination "$POWERDNS_DOCKER_IMAGE":latest
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_COMMIT_MESSAGE =~ /ci-rebuild-powerdns/
    - if: $REBUILD_POWERDNS_CONTAINER == "true"
    - changes:
        - dev/docker/powerdns/Dockerfile

nspect-source-scan-x86_64:
  stage: .pre
  extends: .scan-with-report-no-fail
  allow_failure: true
  variables:
    PULSE_NSPECT_ID: $NSPECT_ID
    PULSE_REPO_URL: "${CI_PROJECT_URL}.git"
    PULSE_SCAN_PROJECT: "carbide"
    PULSE_SCAN_PROJECT_VERSION: "${CI_COMMIT_BRANCH}"
    PULSE_SCAN_VULNERABILITY_REPORT: "nspect_${CI_COMMIT_BRANCH}_scan_report.json"
    PULSE_SCAN_EXCLUDE_DETECTORS: "Setuptools"
  rules:
    - when: never
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_COMMIT_TAG || $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
      variables:
        PULSE_SCAN_OVERRIDE: "true"
        PULSE_REPO_BRANCH: trunk
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_COMMIT_MESSAGE =~ /ci-run-security-scan/

nspect-container-scan-x86_64:
  stage: security
  extends: .scan-dind-override-report
  services: []
  dependencies:
    - get-crane
    - export-docker-json-config
    - build-release-container-x86_64
  needs:
    - job: build-release-container-x86_64
      optional: false
    - job: get-crane
      optional: false
    - job: export-docker-json-config
      optional: false
  variables:
    CONTAINER_IMAGE: $CONTAINER_RELEASE_X86_64
  before_script:
    - mkdir -p /root/.docker
    - cp .docker/config.json /root/.docker/config.json
  script:
    - !reference [.scan_script, validate_requirements]
    - !reference [.scan_script, get_ssa_token]
    - echo "Using $CONTAINER_SCAN_HELPER_VERSION of the container scan helper."
    - ./crane version
    - ./crane pull ${CONTAINER_IMAGE} /tmp/archive.tar
    - pulse-cli -n $NSPECT_ID --ssa $SSA_TOKEN -p .gitlab/runtime-container-policy.json scan --override=true --program-version="Forge-LPR" --is-release=true -i /tmp/archive.tar --sbom json -o
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_COMMIT_TAG || $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH|| $CI_COMMIT_BRANCH =~ /^release\//
      when: never

tag-image-for-nspect-scanning:
  stage: security
  image:
    name: gcr.io/go-containerregistry/crane:debug
    entrypoint: [""]
  dependencies:
    - prepare-ci
    - get-crane
    - export-docker-json-config
    - build-release-container-x86_64
  needs:
    - job: prepare-ci
      optional: false
    - job: get-crane
      optional: false
    - job: export-docker-json-config
      optional: false
    - job: build-release-container-x86_64
      optional: false
  before_script: |
    mkdir -p /root/.docker
    cp .docker/config.json /root/.docker/config.json
  script: |
    set -euo pipefail
    crane copy $APPLICATION_DOCKER_IMAGE:$VERSION $APPLICATION_DOCKER_IMAGE_PRODUCTION:to-be-scanned
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_COMMIT_TAG || $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH || $CI_COMMIT_BRANCH =~ /^release\//

promote-images-to-production:
  stage: promote
  image:
    name: gcr.io/go-containerregistry/crane:debug
    entrypoint: [""]
  needs:
    - job: build-release-artifacts-arm-host
      optional: false
    - job: build-release-artifacts-x86-host
      optional: false
    - job: build-release-container-x86_64
      optional: false
    - job: nspect-container-scan-x86_64
      optional: true
  when: manual
  before_script: |
    mkdir -p /root/.docker
    cp .docker/config.json /root/.docker/config.json
  script: |
    set -euo pipefail
    crane copy $APPLICATION_DOCKER_IMAGE:$VERSION $APPLICATION_DOCKER_IMAGE_PRODUCTION:$VERSION
    crane copy $ARTIFACTS_DOCKER_IMAGE_AARCH64:$VERSION $ARTIFACTS_DOCKER_IMAGE_AARCH64_PRODUCTION:$VERSION
    crane copy $ARTIFACTS_DOCKER_IMAGE_X86_64:$VERSION $ARTIFACTS_DOCKER_IMAGE_X86_64_PRODUCTION:$VERSION
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_COMMIT_TAG || $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH || $CI_COMMIT_BRANCH =~ /^release\//

license-checks:
  stage: security
  image:
    name: $CONTAINER_BUILD_X86_64
  rules:
    - when: never
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - changes:
        - Cargo.lock
        - .license-config.yml
    - if: $CI_COMMIT_TAG
    - if: $CI_PIPELINE_SOURCE != 'merge_request_event'

pages:
  stage: doc
  needs:
    - job: export-docker-json-config
      optional: false
    - job: build-build-container-x86_64
      optional: true
  image:
    name: $CONTAINER_BUILD_X86_64
  script:
    - cargo make book
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH
      when: never
    - changes:
        - book/
    - if: $CI_COMMIT_TAG
    - if: $CI_PIPELINE_SOURCE != 'merge_request_event'

deploy-ipp6-gb200-36x1:
  stage: deploy
  when: manual
  image:
    name: "alpine/k8s:1.29.0" # Example image, choose one compatible with your cluster
    entrypoint: [""]
  script: |
      set -euo pipefail
      mkdir -p ~/.kube
      printf "%s" "$IPP6_36X1_KUBCONFIG" > ~/.kube/config
      export KUBECONFIG=~/.kube/config
      cd deploy/envs/ipp6-gb200-36x1
      kubectl get pods -n forge-system
      kubectl delete  jobs   -n forge-system carbide-api-migrate;
      kustomize build . --enable-helm --enable-alpha-plugins --enable-exec  | kubectl apply -f -
# Runs a test that spins up a single-node Forge control plane (i.e. a dev environment) directly on the GitLab runner and
# checks the health status of all kubernetes resources.
# Intended to be run as a pre-merge test on each MR. Can also be run against trunk.
# Guide here: https://gitlab-master.nvidia.com/nvmetal/ci-tools/internal-services-images/-/blob/main/README.md
#
# TODO: Expand test to cover connecting to an Acorn managed-host
#
# dev-env-test-with-carbide:
#   stage: test
#   tags:
#     - dev-env-carbide
#   rules:
#     - if: $CI_PIPELINE_SOURCE == "schedule" && $DEV_ENV_TEST == "true"
#       changes:
#         - .gitlab/dev-env-test-with-carbide.sh
#         - '.skaffold/**/*'
#         - 'crates/api/**/*'
#         - 'bluefield/**/*'
#         - 'dev/**/*'
#         - 'crates/dhcp/**/*'
#         - 'crates/dhcp-server/**/*'
#         - 'crates/dns/**/*'
#         - 'crates/health/**/*'
#         - 'include/**/*'
#         - 'pxe/**/*'
#         - 'crates/pxe/**/*'
#         - 'crates/rpc/**/*'
#         - 'crates/scout/**/*'
#         - '.envrc'
#         - 'Cargo.lock'
#         - 'Cargo.toml'
#         - 'justfile'
#         - 'Makefile.toml'
#         - 'rust-toolchain.toml'
#         - 'skaffold.yml'
#   retry:
#     max: 1
#   needs:
#     - job: export-docker-json-config
#   variables:
#     VAULT_NAMESPACE: tesla-dcss-rms
#     DEBUG_JUST: #true # Uncomment value for additional logs. Checks test for the presence of variable, therefore setting to false is not equivalent
#     LOG_ARGO: true
#     DPU_NAME: no-dpu  # TODO: Set value when we get an Acorn managed-host to include in test
#   id_tokens:
#     VAULT_JWT_TOKEN:
#       aud: $VAULT_ADDR
#   before_script:
#     - set -euo pipefail
#     - if [ -n "${DEBUG_JUST}" ] ; then set -xv; fi
#     - mkdir -p ~/.docker
#     - cp .docker/config.json ~/.docker/config.json
#     - export VAULT_JWT_ROLE=$VAULT_JWT_ROLE_FORGE
#     - export VAULT_JWT_PATH=$VAULT_JWT_PATH_FORGE
#     - export VAULT_TOKEN="$(vault write -field=token $VAULT_JWT_PATH role=$VAULT_JWT_ROLE jwt=$VAULT_JWT_TOKEN)"
#   script:
#     - .gitlab/dev-env-test-with-carbide.sh
#   after_script:
#     - set -euo pipefail
#     - cp /tmp/argo_watch.log .
#     - cp /tmp/argo_logs.log .
#     - cp /tmp/container-build.log .
#     - cp /tmp/pxe-build-aarch.log .
#     - cp /tmp/pxe-build-x86.log .
#     - cd ../forged
#     - source /root/.bashrc
#     - eval "$(direnv export bash)"
#     - just clean
#     - docker system prune --force --all
#     - echo "Clean-up complete!"
#   artifacts:
#     when: always
#     paths:
#       - argo_logs.log
#       - argo_watch.log
#       - container-build.log
#       - pxe-build-aarch.log
#       - pxe-build-x86.log
